version: '{build}'

before_build:
  - dotnet restore

build_script:
  - dotnet build src\FileSignatures -c Release

after_build:
  - dotnet pack src\FileSignatures -c Release -o .\artifacts

test_script:
  - dotnet test test\FileSignatures.Tests -c Release -appveyor

artifacts:
  - path: '.\artifacts\**\*.nupkg'
    name: NuGet Package