version: '{build}'

configuration: Release

build:
  project: FileSignatures.sln

after_build:
  - dotnet pack src\FileSignatures -c Release -o ..\..\artifacts

artifacts:
  - path: '.\artifacts\*.nupkg'
    name: NuGet Package

deploy:
  - provider: NuGet
    name: production
    api_key:
      secure: Br035jyTit8hIaWNRZl10uL5LZIYTVtN2NF4jOwfisuEfA3SadxoCM/p1mpe5j+Y
    on:
      appveyor_repo_tag: true
