version: '{build}'

before_build:
  - dotnet restore

build_script:
  - dotnet build

after_build:
  - dotnet pack

test_script:
  - cd test\FileSignatures.Tests
  - dotnet test -appveyor
  
artifacts:
  - path: '**\*.nupkg'
    name: NuGet Package